apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-app
      tier: backend
    # matchExpressions:
    #   - {key: app, operator: In, values: [node-app]}
  template:
    metadata:
      labels:
        app: node-app
        tier: backend
    spec:
      containers:
      - name: node-app-pod
        image: ashishyd/kub-node-app:v2
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10